const ChromecastReceiverEvents = [
    'messageReceived',
    'requestLoad',
    'setCredentials',
    'editAudioTrack',
    'editTracksInfo',
    'loadByEntity',
    'userAction',
    'displayStatus',
    'customCommand',
    'focusState',
    'queueLoad',
    'queueInsert',
    'queueUpdate',
    'queueRemove',
    'queueReorder',
    'queueGetItemRange',
    'queueGetItems',
    'queueGetItemsIndex',
    'castError',
    'playerLoading',
    'playerPreloading',
    'playerPreloadingCancelled',
    'canPlay',
    'playerWaiting',
    'loadStart',
    'connectionDrop',
    'connectionRestored',
    'castReady',
    'requestShutdown',
    'castShutdown',
    'castSenderConnected',
    'castSenderDisconnected',
    'castError',
    'castVolumeChanged',
    'castVisibilityChanged',
    'castStandbyChanged',
    'castMaxVideoResolutionChanged',
    'castFeedbackStarted',
    // standard cast messages

];

export default ChromecastReceiverEvents;
